name: JSON Check

on:
    pull_request:
        paths:
            - "src/**.json"

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: json-syntax-check
              uses: limitusus/json-syntax-check@v2
              with:
                pattern: "\\.json$"